site_name: Flutter KApp Docs
site_author: Kuloud
site_url: https://kuloud.github.io/flutter_kapp

repo_name: kuloud/flutter_kapp
repo_url: https://github.com/kuloud/flutter_kapp

copyright: Copyright &copy; 2025 Kuloud

docs_dir: docs
nav:
  - Home: index.md
  - 组件库:
    - Web3Auth: components/web3auth.md
  - API 参考:
    - AuthService: api/auth_service.md
  - 开发指南:
    - 环境配置: guides/env_setup.md
    - 代码规范: guides/coding_standards.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - toc.integrate
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kuloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xkuloud