site_name: Flutter KApp Docs
docs_dir: docs
nav:
  - Home: index.md
  - Components:
    - Web3Auth: components/web3auth.md
theme:
  name: readthedocs
  toc_title: "On this page"

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2